cloudogu/usermgt

src/main/webapp/views/user/edit.html
resolves [https://github.com/cloudogu/ecosystem/issues/136](url)
=> fixed removing and editing of groups

app/src/main/webapp/scripts/constrainthandling/services.js, app/src/main/webapp/views/user/edit.html
Fix some misspelled error messages.
=> Change some error messages

CHANGELOG.md, Jenkinsfile, app/src/main/webapp/scripts/passwordpolicy/services.js
Fixed bug where no error was shown on invalid password policy or when the endpoint could not be reached
=> Update password policy error handling

CHANGELOG.md, app/src/main/webapp/index.html, app/src/main/webapp/views/group/edit.html, app/src/main/webapp/views/group/groups.html, app/src/main/webapp/views/user/edit.html, app/src/main/webapp/views/user/users.html
Change order of input-groups for convenience with assistive technologies
Titles relate closer to subject
Fix small accessibility-issues
resolves #34
=> Make forms more accessible

app/src/main/webapp/style/less/custom.less
remove definition to use new definition from ces-theme.
refer to https://github.com/cloudogu/ces-theme/issues/21
=> remove locale definition of warning button 

CHANGELOG.md, app/src/main/java/de/triology/universeadm/CasRestClient.java
=> [#37] Fix incorrect content type

CHANGELOG.md, Dockerfile
- Upgrade java base image to 8u302-1
- Upgrade all packages to get zlib 1.2.12
Resolves #49
=> Upgrade base image and packages

CHANGELOG.md, resources/startup.sh
=> Remove source of etc/ces/functions.sh

CHANGELOG.md, app/src/main/webapp/scripts/users/controllers.js, app/src/main/webapp/views/user/edit.html
=> #51 Fix pwd-reset

CHANGELOG.md, app/src/main/java/de/triology/universeadm/user/imports/CSVParserImpl.java, app/src/main/java/de/triology/universeadm/user/imports/CsvLineNumberReader.java, app/src/test/java/de/triology/universeadm/user/imports/CSVParserTest.java
=> Bugfix - csv import multiple users

CHANGELOG.md, app/src/main/java/de/triology/universeadm/mail/MailServiceImpl.java
=> #128 escape passwords in notification email for new users

CHANGELOG.md, Jenkinsfile, resources/migration/givenName-migration.sh
=> #130 fix givenNameMigration.sh wrap problem

CHANGELOG.md, app/src/main/ui/src/components/groups/GroupForm.tsx, app/src/main/ui/src/hooks/useUserFormHandler.ts, integrationTests/cypress/e2e/group_create.feature, integrationTests/cypress/e2e/password_policy.feature, integrationTests/cypress/e2e/user_create.feature, integrationTests/cypress/support/step_definitions/when.ts
=> #137 only validate on submit

CHANGELOG.md, app/src/main/java/de/triology/universeadm/mapping/MappingHandler.java
=> #139 only validate when group name has changed

app/src/main/java/de/triology/universeadm/user/User.java
=> While adding a user some email adresses are shown as valid by the frontend but invalid by the backend

app/src/main/ui/src/components/groups/GroupForm.tsx, app/src/main/ui/src/hooks/useUserFormHandler.ts, integrationTests/cypress/support/step_definitions/then.ts
=> #137 Only show errors and not success

.gitignore, CHANGELOG.md, Makefile, batsTests/logging.bats, build/make/k8s-dogu.mk, dogu.json, resources/logging.sh, resources/post-upgrade.sh, resources/startup.sh
Move state that should be persistent between restarts to local config.
Resolves #142
=> #142 Use local config for persistent state

CHANGELOG.md, app/src/main/ui/src/components/groups/GroupForm.tsx, app/src/main/ui/src/components/users/UserForm.tsx, app/src/main/ui/src/i18n/de.json, app/src/main/ui/src/i18n/en.json, docs/gui/release_notes_de.md, docs/gui/release_notes_en.md
=> mark optional fields in forms

CHANGELOG.md, app/src/main/java/de/triology/universeadm/ValidMailConstraint.java, app/src/main/ui/src/components/usersImport/UsersImportTable.tsx, app/src/test/java/de/triology/universeadm/ValidMailConstraintTest.java, docs/gui/release_notes_de.md, docs/gui/release_notes_en.md
=> #170, #171 Do not allow mails with multiple '@' and set the page size to 25 on user import page

CHANGELOG.md, docs/gui/documentation_en.md
=> fix list in gui docs

CHANGELOG.md, app/src/main/ui/src/components/users/UserForm.tsx
=> Only show external-user-hint if user is marked as external

app/src/main/ui/src/pages/Users.tsx
* just display the email as plain-text to prevent automated opening of custom email-client
=> #179 remove mailto link from user list

.gitignore, CHANGELOG.md, batsTests/logging.bats, dogu.json, resources/logging.sh, resources/startup.sh
=> #193 add missing key in dogu descriptor

CHANGELOG.md, docs/gui/release_notes_de.md, docs/gui/release_notes_en.md, dogu.json
=> #200 Set sensible resource requests and limits
